python create_pretraining_data.py \
--input_file=$INPUT_FILE \
--output_dir=$OUTPUT_DIR \
--vocab_file=vocabs/bert-cased-vocab.txt \
--do_lower_case=False \
--do_whole_word_mask=False \
--max_seq_length=512 \
--max_predictions_per_seq=80 \
--num_processes=63 \
--masked_lm_prob=0.15 \
--dupe_factor=5 \
--geometric_masking_p=0.2 \
--max_span_length=10 \
--recurring_span_selection=False \
--only_recurring_span_selection=False